apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: longhorn-system

resources:
  - install.yaml
  - settings/default-data-path.yaml


patches:
  - path: namespace-patch.yaml
    target:
      kind: Namespace
      name: longhorn-system
  # - path: settings/default-data-path.yaml
  #   target:
  #     name: default-data-path
  #     kind: Setting
