apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: longhorn-system

resources:
  - install.yaml


patches:
  - path: namespace-patch.yaml
    target:
      kind: Namespace
      name: longhorn-system
  - path: default-settings-patch.yaml
    target:
      name: longhorn-default-setting
      kind: ConfigMap
