apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # kustomize build "github.com/rancher/local-path-provisioner/deploy?ref=v0.0.34" > install.yaml
  - install.yaml
patches:
  - path: namespace.yaml
  - path: configmap.yaml
  - path: storageclass.yaml
