deployments:
  - path: backbone/metallb
  - path: backbone/cert-manager
  - path: backbone/envoy-gateway-system
    waitReadiness: true
  - path: backbone/gateways


  - path: deployments/nginx-test


