deployments:
  - path: backbone/metallb
  - path: backbone/cert-manager
  - path: backbone/envoy-gateway-system
    waitReadiness: true
  - path: backbone/gateways
    waitReadiness: true

  - path: backbone/longhorn
    waitReadiness: true


  - path: deployments/nginx-test


