apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: immich

resources:
  - namespace.yaml
  - cloudnative-pg.yaml
  - pvc.yaml
  - immich-config.yaml
  - helm-render/install.yaml
  - httproute.yaml
  - photos-backup-cronjob.yaml
  - external-secret.yaml
