apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-user-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      # being ignored by immich, I think this is a local-path-provsioner limitation
      storage: 48Gi
