serviceDns:
  loadBalancerIP: "192.168.1.14"
  type: ClusterIP
serviceDhcp:
  enabled: false
persistentVolumeClaim:
  enabled: true
  size: "1Gb"
  storageClass: "local-path"
admin:
  enabled: true
  existingSecret: "pihole-password"
  passwordKey: "password"
