apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system
resources:
  - install.yaml
  - config/metallb-config.yaml

patches:
  - target:
      group: apps
      version: v1
      kind: DaemonSet
      name: speaker
      namespace: metallb-system
    path: patch-fix-speaker-lb.yaml
