apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pihole-admin
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: pihole-password
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: pihole-password
