apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pihole

resources:
  - namespace.yaml
  - helm-render/install.yaml
  - external-secret.yaml
  - env-cm.yaml
  - routes.yaml


patches:
  # add our config map
  - target:
      kind: Deployment
      name: pihole
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/envFrom
        value: 
          - configMapRef:
              name: pihole-env
