apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets
# installed the crds with curl -O https://raw.githubusercontent.com/external-secrets/external-secrets/v2.3.0/deploy/crds/bundle.yaml
resources:
  - namespace.yaml
  - helm-render/install.yaml
  - crds.yaml
  - bitwarden/issuer.yaml
  - bitwarden/certs.yaml
  - issuer.yaml
  - certs.yaml
  - bitwarden/cluster-secret-store.yaml
  # - bitwarden/token-secret.yaml # manually generated see README
