apiVersion: v1
kind: Pod
metadata:
  name: mekaniq
spec:
  containers:
    - name: main
      image: ghcr.io/jopjeknopje/mekaniq:main
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo app1:$(date -u) >> /data/test.log; sleep 5; done"]
      volumeMounts:
        - mountPath: /home/pvc
          name: pihole
  volumes:
    - name: pihole
      persistentVolumeClaim:
        claimName: pihole # Your PVC you want to backup
