apiVersion: v1
kind: Pod
metadata:
  name: mekaniq
spec:
  containers:
    - name: main
      image: ghcr.io/jopjeknopje/mekaniq:main
      command: ["/bin/sh"]
      args: ["-c", "while true; sleep 5; done"]
