apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# This namespace holds all of our Gateways and cert-manager Issuer(s) for our
# different services.  It shouldn't run any services.
namespace: gateways
resources:
  - namespace.yaml
  - envoy-gateway.yaml
  - envoy-cert-manager-issuer.yaml
  - envoy-redirect-httproute.yaml
